# Generated by Django 3.2 on 2023-03-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Вид питомца')),
                ('description', models.TextField(verbose_name='Описание вида питомца')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг питомца для ссылки')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода питомца')),
                ('description', models.TextField(verbose_name='Описание породы питомца')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг породы питомца')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картика питомца')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Время изменения записи')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kindofanimals', verbose_name='Вид питомца')),
            ],
            options={
                'ordering': ('-pub_date', 'breed'),
            },
        ),
    ]
